import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 14,
  tables: [
    tableSchema({
      name: 'merchants',
      columns: [
        { name: 'entity_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'logo_url', type: 'string', isOptional: true },
        { name: 'website', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'accounts',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'item_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'official_name', type: 'string', isOptional: true },
        { name: 'type', type: 'string' },
        { name: 'subtype', type: 'string' },
        { name: 'mask', type: 'string', isOptional: true },
        { name: 'balance_current', type: 'number' },
        { name: 'balance_available', type: 'number', isOptional: true },
        { name: 'iso_currency_code', type: 'string', isOptional: true },
        { name: 'unofficial_currency_code', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'transactions',
      columns: [
        { name: 'transaction_id', type: 'string', isIndexed: true },
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'merchant_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'amount', type: 'number' },
        { name: 'iso_currency_code', type: 'string', isOptional: true },
        { name: 'unofficial_currency_code', type: 'string', isOptional: true },
        { name: 'category_id', type: 'string', isOptional: true },
        { name: 'check_number', type: 'string', isOptional: true },
        { name: 'date', type: 'string' },
        { name: 'authorized_date', type: 'string', isOptional: true },
        { name: 'authorized_datetime', type: 'string', isOptional: true },
        { name: 'datetime', type: 'string', isOptional: true },
        { name: 'payment_channel', type: 'string' },
        {
          name: 'personal_finance_category_primary',
          type: 'string',
          isOptional: true,
        },
        {
          name: 'personal_finance_category_detailed',
          type: 'string',
          isOptional: true,
        },
        {
          name: 'personal_finance_category_confidence_level',
          type: 'string',
          isOptional: true,
        },
        {
          name: 'personal_finance_category_icon_url',
          type: 'string',
          isOptional: true,
        },
        { name: 'name', type: 'string' },
        { name: 'merchant_name', type: 'string', isOptional: true },
        { name: 'merchant_entity_id', type: 'string', isOptional: true },
        { name: 'logo_url', type: 'string', isOptional: true },
        { name: 'website', type: 'string', isOptional: true },
        { name: 'pending', type: 'boolean' },
        { name: 'transaction_code', type: 'string', isOptional: true },
        { name: 'counterparties', type: 'string', isOptional: true },
        { name: 'source', type: 'string', isOptional: true },
        { name: 'budget_item_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'items',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'plaid_item_id', type: 'string', isIndexed: true },
        { name: 'item_api_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'institution_id', type: 'string' },
        { name: 'institution_name', type: 'string' },
        { name: 'institution_logo', type: 'string', isOptional: true },
        { name: 'institution_primary_color', type: 'string', isOptional: true },
        { name: 'institution_url', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'last_successful_update', type: 'string', isOptional: true },
        { name: 'last_local_refresh', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_active', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'syncs',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'plaid_item_id', type: 'string', isIndexed: true },
        { name: 'action', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'categories',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'primary', type: 'string' },
        { name: 'detailed', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'icon', type: 'string', isOptional: true },
        { name: 'color', type: 'string', isOptional: true },
        { name: 'ignored', type: 'boolean' },
        { name: 'children', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'transaction_syncs',
      columns: [
        { name: 'plaid_item_id', type: 'string', isIndexed: true },
        { name: 'transactions_update_status', type: 'string' },
        { name: 'next_cursor', type: 'string' },
        { name: 'has_more', type: 'boolean' },
        { name: 'request_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'budgets',
      columns: [
        { name: 'start_date', type: 'number' },
        { name: 'end_date', type: 'number' },
        { name: 'balance', type: 'number' },
        { name: 'balance_source', type: 'string' },
        { name: 'account_balance_source', type: 'string' },
        { name: 'account_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'duration', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'status', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'budget_items',
      columns: [
        { name: 'budget_id', type: 'string', isIndexed: true },
        { name: 'funding_account_id', type: 'string', isOptional: true },
        { name: 'merchant_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'category_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'type', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'tracking_mode', type: 'string', isOptional: true },
        { name: 'due_date', type: 'number', isOptional: true },
        { name: 'is_auto_pay', type: 'boolean', isOptional: true },
        { name: 'exclude_from_balance', type: 'boolean', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'account_daily_balances',
      columns: [
        { name: 'account_id', type: 'string', isIndexed: true },
        { name: 'balance', type: 'number' },
        { name: 'date', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'item_id', type: 'string', isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'logs',
      columns: [
        { name: 'type', type: 'string', isIndexed: true },
        { name: 'level', type: 'string', isIndexed: true },
        { name: 'message', type: 'string' },
        { name: 'metadata', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
