const tintColorLight = '#973AFF';
const tintColorDark = '#973AFF';

export const Colors = {
  primary: '#973AFF',
  secondary: '#3A7BFF',
  tertiary: '#2C9AC6',
  quaternary: '#DE32E4',
  negative: 'transparent',
  success: '#20b197',
  pending: '#1090c7',
  warning: '#ffa334',
  error: '#ff4d4f',
  alert: '#ff6a00',
  limeGreen: '#32CD32',
  white: '#ffffff',
  black: '#000000',
  light: {
    text: '#11181C',
    textSecondary: '#687076',
    background: '#ffffff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    backgroundSecondary: '#ffffff',
    backgroundTertiary: '#f0f0f0',
    disabled: '#CDCDCD',
  },
  dark: {
    text: '#ECEDEE',
    textSecondary: '#BCBCBC',
    background: '#040607',
    backgroundSecondary: '#191819',
    backgroundTertiary: '#2d2d2d',
    tint: tintColorDark,
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
    disabled: '#CDCDCD',
  },
};
